Repository skalpel-tech/ldtscrm, pull requests merged in 2019-01, with the labels that each got.

#62 Add Slack Badge
  README.md
Labels: documentation

#61 initial commit for documentation
  docs/_config.yaml
  docs/design.md
  docs/index.md
  docs/roadmap.md
Labels: documentation

#55 Integrate with postgres
  .pylintrc
  README.md
  app/__init__.py
  app/api/business/contacts/models.py
  app/api/business/contacts/resource.py
  app/api/business/contacts/schemas.py
  app/api/business/contacts/services.py
  app/extensions/__init__.py
  app/extensions/flask_sqlalchemy/__init__.py
  app/requirements.txt
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/b53c2fec1623_.py
  tasks/app/__init__.py
  tasks/app/_utils.py
  tasks/app/db.py
  tasks/app/db_templates/flask/alembic.ini
  tasks/app/db_templates/flask/alembic.ini.mako
  tasks/app/db_templates/flask/env.py
  tasks/app/db_templates/flask/script.py.mako
Labels: enhancement

#97 Moved restplus bootstrap to extensions
  app/__init__.py
  app/core/entity/schemas.py
  app/extensions/api/__init__.py
  app/extensions/api/restplus.py
Labels: architecture
